name: Publish to Docker Hub

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  FRONT_IMAGE_NAME: ${{ github.repository }}-frontend
  BACK_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  push-front-to-registry:
    name: Publish frontend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add front metadata for Docker Hub
        id: meta-front
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE_NAME }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          tags: ${{ steps.meta-front.outputs.tags }}
          labels: ${{ steps.meta-front.outputs.labels }}

  push-back-to-registry:
    name: Publish backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add back metadata for Docker Hub
        id: meta-back
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          push: true
          tags: ${{ steps.meta-back.outputs.tags }}
          labels: ${{ steps.meta-back.outputs.labels }}
